### ISSUE TITLE
Please add weaponskins, knife and gloves commands.

### ISSUE THREAD

**Issue by B3none** [b3none/meloncartel#1]
**Is your feature request related to a problem? Please describe.**
Lack of new players joining afresh.

**Describe the solution you'd like**
I'd like these plugins to be added to the servers.

**Describe alternatives you've considered**
Perhaps suggest our servers manually and get a cleaner player base with less abuse. Full servers do not necessarily need to be very popular.

**Additional context**
I feel that if we're able to implement `!ws`, `!knife` and `!gloves` then new players will be more likely to join the servers.

**Comment by B3none** [comment]
Update:
This is likely to be added over the next month.

**Comment by B3none** [comment]
Added.

**Comment by bariod** [comment]
As a follow up: What about adding a "random" option for every gun? @b3none
