### ISSUE TITLE
Missing files for map change plugin

### ISSUE THREAD

**Issue by RyanBlackham** [b3none/meloncartel#2]
**Describe the bug**
It's giving me lots of console errors saying that there are missing files.

**To Reproduce**
1. Join the server
2. Check the console for errors

**Expected behavior**
It should just download the files.

**Screenshots**
![20180625171348_1](https://user-images.githubusercontent.com/40574343/41862225-29ec6af4-789b-11e8-8967-f7463aa464a9.jpg)

**Comment by B3none** [comment]
Update:
I've resolved this, I've now setup the config correctly. Let me know if this works for you, if not you can download the files manually at: https://dl.gamssi.com/
